---
title: "WW_Genotyper-v4"
author: "Tomas de Melo"
date: "2025-09-26"
output: html_document
---

```{r Packages, include=FALSE}
#install.packages(c("BiocManager","dplyr", "openxlsx", "ggplot2"))
#BiocManager::install("Biostrings")
#BiocManager::install("Rsamtools")
library(Rsamtools)
library(dplyr)
library(openxlsx)
library(Biostrings)
library(BiocManager)
library(ggplot2)
library(msa)
```

```{r setup}
#File with file and corresponding date of sample 
df <- read.xlsx("WW_samples.xlsx", sheet = "Sheet1")
fasta_file_mapping <- setNames(df$date, df$file)

#Set working directory
setwd("enter/working/directory/file/path")

#Colour palette
cArray <- c(
  "dodgerblue2", "#E31A1C", "firebrick","#6A3D9A", "#FF7F00", "black", "gold1",
  "skyblue2", "#FB9A99", "palegreen2", "#CAB2D6",  "#FDBF6F",  "gray70",
  "khaki2", "maroon", "orchid1", "deeppink1", "blue1", "forestgreen",
  "darkturquoise", "green1", "yellow4", "yellow3","darkorange4", "brown",'black','forestgreen', 'red2', 'orange', 'cornflowerblue', 
  'magenta', 'darkolivegreen4', 'indianred1', 'tan4', 'darkblue', 
  'mediumorchid1','firebrick4',  'yellowgreen', 'lightsalmon', 'tan3',
  "tan1",'darkgray', 'wheat4', '#DDAD4B', 'chartreuse', 
  'seagreen1', 'moccasin', 'mediumvioletred', 'seagreen','cadetblue1',
  "darkolivegreen1" ,"tan2" ,   "tomato3" , "#7CE3D8","gainsboro","dodgerblue2", "#E31A1C", "green4","#6A3D9A", "#FF7F00", "black", "gold1",
  "skyblue2", "#FB9A99", "palegreen2", "#CAB2D6",  "#FDBF6F",  "gray70",
  "khaki2", "maroon", "orchid1", "deeppink1", "blue1", "steelblue4",
  "darkturquoise", "green1", "yellow4", "yellow3","darkorange4", "brown",'black','forestgreen', 'red2', 'orange', 'cornflowerblue', 
  'magenta', 'darkolivegreen4', 'indianred1', 'tan4', 'darkblue', 
  'mediumorchid1','firebrick4',  'yellowgreen', 'lightsalmon', 'tan3',
  "tan1",'darkgray', 'wheat4', '#DDAD4B', 'chartreuse', 
  'seagreen1', 'moccasin', 'mediumvioletred', 'seagreen','cadetblue1',
  "darkolivegreen1" ,"tan2" ,   "tomato3" , "#7CE3D8","gainsboro","orange","yellow","red","maroon"
)

#Paths to BLAST
blast_bin <- "path/to/BLAST/ncbi-blast-2.16.0+/bin"
makeblastdb <- file.path(blast_bin, "makeblastdb")
blastn <- file.path(blast_bin, "blastn")

#Input data
types <- "all_viral_types_combined.fasta"
WW_reads <- list.files(pattern = "^barcode[0-96]+\\_combined.fasta$")
db_name <- "viral_Reference_Sequences"
excel_file <- "blast_top_hits_by_sample.xlsx"
sheet_name <- "partial seq"

#Create BLAST database
if (!file.exists(paste0(db_name, ".nin"))) {
  cat("Creating BLAST database from reference file...\n")
  system(paste(shQuote(makeblastdb), "-in", types, "-dbtype nucl -out", db_name))
} else {
  cat("BLAST database already exists. Skipping creation.\n")
}

wb <- createWorkbook()

#To store total queries per sample
total_queries_list <- list()

```

```{r Blast}
for (query in WW_reads){
  
  cat("Checking if", query, "results exists...\n")
  out_file <- sub("\\.fasta$", "_blast_results.txt", query)
  
  if (!file.exists(out_file)){
    
    
    #Run BLAST
    cat("Running BLAST for", query, "...\n")
    
    out_file <- sub("\\.fasta$", "_blast_results.txt", query)
    
    #Run BLAST
    system(paste("blastn -query", query, "-db", db_name, "-outfmt 6 -out ", out_file,"-task dc-megablast -num_threads 8 -evalue 1e-3 -word_size 12"))
    query_seqs <- readDNAStringSet(query)
    total_queries <- length(query_seqs)
    total_queries_list[[query]] <- total_queries
    
    #Skip if no hits
    if (file.info(out_file)$size == 0) {
      warning("No hits found for ", query)
      results <- data.frame()
    } else {
      results <- read.table(out_file, header = TRUE, sep = "\t",
                            col.names = c("query", "subject", "pident", "length",
                                          "mismatch", "gapopen", "qstart", "qend",
                                          "sstart", "send", "evalue", "bitscore"))
    }
  } else {
    
    cat(query, "results exists, loading into workbook...\n")
    #Read query sequences to count total reads
    query_seqs <- readDNAStringSet(query)
    total_queries <- length(query_seqs)
    total_queries_list[[query]] <- total_queries
    
    #Skip if no hits
    if (file.info(out_file)$size == 0) {
      warning("No hits found for ", query)
      results <- data.frame()
    } else {
      results <- read.table(out_file, header = FALSE, sep = "\t",
                            col.names = c("query", "subject", "pident", "length",
                                          "mismatch", "gapopen", "qstart", "qend",
                                          "sstart", "send", "evalue", "bitscore"))
      results$source_file <- query
    }
    
    
    attr(results, "total_queries") <- total_queries
    
    #Get top hit per query
    if (nrow(results) > 0) {
      top_hits <- results %>%
        group_by(query) %>%
        top_n(1, bitscore) %>%
        ungroup()
    } else {
      top_hits <- data.frame()
    }
    
    attr(top_hits, "total_queries") <- total_queries
    
    #Clean Excel sheet name
    sheet_name <- gsub("\\.fasta$", "", query)
    sheet_name <- substr(sheet_name, 1, 31)
    
    #Write to workbook
    addWorksheet(wb, sheet_name)
    writeData(wb, sheet = sheet_name, top_hits)
  }
}
#Save workbook with all top hits
saveWorkbook(wb, excel_file, overwrite = TRUE)
sheets <- getSheetNames(excel_file)

summary_list <- list()

for (sheet in sheets) {
  data <- read.xlsx(excel_file, sheet = sheet)
  fasta_file <- paste0(sheet, ".fasta")
  sample_date <- fasta_file_mapping[[fasta_file]]
  if (is.null(sample_date)) sample_date <- sheet
  if(is.null(data)) {data<-data.frame()}
  total_queries <- total_queries_list[[fasta_file]]
  
  #Summarize hits if present
  if (nrow(data) > 0) {
    summary <- data %>%
      group_by(subject) %>%
      summarise(count = n(), avg_pident = mean(pident), .groups = "drop")
    
    assigned_count <- sum(summary$count)
  } else {
    summary <- tibble(subject = character(), count = integer(), avg_pident = numeric())
    assigned_count <- 0
  }
  
  unassigned_count <- total_queries - assigned_count
  if (unassigned_count > 0) {
    summary <- bind_rows(
      summary,
      tibble(subject = "Could not assign", count = unassigned_count, avg_pident = NA)
    )
  }
  
  summary <- summary %>%
    mutate(sample = sample_date, total_hits = sum(count))
  
  summary_list[[sheet]] <- summary
}

#Combine all summaries
summary_df <- bind_rows(summary_list)


#Calculate percentages
genotype_percentage_results <- summary_df %>%
  group_by(sample) %>%
  mutate(Percentage = (count / sum(count)) * 100) %>%
  select(sample, genotype = subject, Percentage, total_hits,avg_pident)

#Set order of samples
desired_order <- fasta_file_mapping %>% unname()
genotype_percentage_results$sample <- factor(genotype_percentage_results$sample, levels = desired_order)

#Group low abundance genotypes, exclude "Could not assign"
genotype_percentage_results <- genotype_percentage_results %>%
  mutate(genotype = if_else(Percentage < 5 & genotype != "Could not assign", "Other", genotype))

#Removes low read counts <100
genotype_percentage_results <- genotype_percentage_results[genotype_percentage_results$total_hits >= 100, ]

addWorksheet(wb, "NV")
writeData(wb, sheet = "NV", genotype_percentage_results)
saveWorkbook(wb, "genotype_pc_results.xlsx", overwrite = TRUE)

```


```{r Plotting}
ggplot(genotype_percentage_results, aes(x = sample, y = Percentage, fill = genotype)) +
  geom_bar(stat = "identity", position = "stack") +
  theme_minimal() +
  scale_fill_manual(values = cArray) +
  labs(x = "Samples", y = "Relative Abundance", fill = "Genotype") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank())

```

```{r Genotype Consensus over time}
target_subject <- c("GII.2","GII.4","GII.6")
#target_subject <- unique(genotype_percentage_results$genotype) #Requires a lot of RAM

datas_list <- list()
peptide_seqs <- data.frame()
cons_seqs <- data.frame()

i <- 1
for (genotype in target_subject){
  print(genotype)
  refseq <- readDNAStringSet(types) 
  if(length(target_subject)==1){
    refseq <- refseq[names(refseq) %in% target_subject]
  } else {
    refseq <- refseq[names(refseq) %in% target_subject[genotype]]
  }
  
  for (sheet in sheets) {
    data <- read.xlsx(excel_file, sheet = sheet)
    required_cols <- c("query", "pident","subject", "source_file","length","qstart","qend","sstart","send")
    data_selected <- data[, required_cols]
    datas_list[[sheet]] <- data_selected %>%
      filter(pident>90)
  }
  
  if (length(datas_list) > 0) {
    aggregated_data <- do.call(rbind, datas_list)
    print("Success...sheets had required columns")
  } else {
    print("No sheets found or none had required columns.")
  }
  
  subject_groups <- aggregated_data %>%
    group_by(subject) %>%
    #filter(!is.na(subject)) %>%
    group_split()
  
  subject_tibbles_list <- list()
  
  for (group in subject_groups) {
    subject_name <- group$subject[1]
    source_splits <- split(group, group$source_file)
    source_tibbles <- list()
    for (src_file in names(source_splits)) {
      source_tibbles[[src_file]] <- source_splits[[src_file]]
    }
    subject_tibbles_list[[subject_name]] <- source_tibbles
  }
  target_genotype <- subject_tibbles_list[[genotype]]
  
  if(!is.null(subject_tibbles_list[[genotype]])){
    
    for (sampleID in target_genotype) {
      if(length(sampleID$subject)>10000){#&& length(sampleID$subject)<15000){
        #file <- readDNAStringSet(sampleID$source_file)
        #filtered_dna <- file[names(file) %in% sampleID$query]
        #filtered_dna <- unique(filtered_dna)
        
        lapply(unique(sampleID$source_file), indexFa)
        filtered_dna <- do.call(c, lapply(unique(sampleID$source_file), function(f) {
          fa <- FaFile(f)
          open(fa)
          idx <- scanFaIndex(fa)
          wanted <- idx[as.character(seqnames(idx)) %in% sampleID$query]
          seqs <- scanFa(fa, wanted)
          close(fa)
          seqs
        }))
        
        qstart <- target_genotype[[sampleID$source_file[1]]]$qstart
        qend <- target_genotype[[sampleID$source_file[1]]]$qend
        
        sstart <- target_genotype[[sampleID$source_file[1]]]$sstart
        send <- target_genotype[[sampleID$source_file[1]]]$send
        refseq <- subseq(refseq, start = min(sstart), end = max(send))
        
        print(length(qstart)-length(filtered_dna))
        if ((length(qstart)-length(filtered_dna))!=0){
          print(paste("Failed due to differing variable lengths (see qstart/qend and filtered_dna)...skipping fasta file",sampleID$source_file[1]))
        }else{
          dna_segments <- subseq(filtered_dna, start = qstart, end = qend)
          all_seqs<-c(refseq,dna_segments)
          aligned <- msaMuscle(all_seqs, gapOpening = 4000, gapExtension = 50, verbose = TRUE)
          cons_matrix <- consensusMatrix(aligned, baseOnly=TRUE)
          cons_matrix <- cons_matrix[-nrow(cons_matrix), ]
          cons <- consensusString(cons_matrix, ambiguityMap="N", threshold= 0.5)
          #cons <- gsub("\\?", "N", cons)
          print(cons)
          cons_seqs[i, "file"] <- fasta_file_mapping[sampleID$source_file[1]]
          cons_seqs[i, "file"] <- gsub("\\/", "-",  cons_seqs[i, "file"])
          cons_seqs[i, "DNAseq"] <- cons
          cons_seqs[i, "genotype"] <- genotype
        }
      }else{
        print("Less than 100 reads found for this barcode...")
      }
      i <- i+1
    }
    
  }
}
cons_seqs <- cons_seqs %>%
  filter(!is.na(cons_seqs$DNAseq))
print(cons_seqs)


consensuses <- DNAStringSet(cons_seqs$DNAseq)
consensuses@ranges@NAMES <- paste0(cons_seqs$genotype,"_",cons_seqs$file)
writeXStringSet(consensuses, file = "WW-derived_Consensus-sequences.fasta" )
```
