---
title: "WW_Genotyper-v2_Validation"
author: "Tomas de Melo"
date: "2025-09-25"
output: html_document
---

```{r Packages, include=FALSE}
#install.packages(c("BiocManager","dplyr", "openxlsx", "ggplot2"))
#BiocManager::install("Biostrings")

library(dplyr)
library(openxlsx)
library(Biostrings)
library(BiocManager)
library(ggplot2)

```

```{r setup}

#Set working directory
setwd("enter/working/directory/file/path")

#Colour palette
cArray <- c(
  "dodgerblue2", "#E31A1C", "green4","#6A3D9A", "#FF7F00", "black", "gold1",
  "skyblue2", "#FB9A99", "palegreen2", "#CAB2D6",  "#FDBF6F",  "gray70",
  "khaki2", "maroon", "orchid1", "deeppink1", "blue1", "steelblue4",
  "darkturquoise", "green1", "yellow4", "yellow3","darkorange4", "brown",'black','forestgreen', 'red2', 'orange', 'cornflowerblue', 
  'magenta', 'darkolivegreen4', 'indianred1', 'tan4', 'darkblue', 
  'mediumorchid1','firebrick4',  'yellowgreen', 'lightsalmon', 'tan3',
  "tan1",'darkgray', 'wheat4', '#DDAD4B', 'chartreuse', 
  'seagreen1', 'moccasin', 'mediumvioletred', 'seagreen','cadetblue1',
  "darkolivegreen1" ,"tan2" ,   "tomato3" , "#7CE3D8","gainsboro","dodgerblue2", "#E31A1C", "green4","#6A3D9A", "#FF7F00", "black", "gold1",
  "skyblue2", "#FB9A99", "palegreen2", "#CAB2D6",  "#FDBF6F",  "gray70",
  "khaki2", "maroon", "orchid1", "deeppink1", "blue1", "steelblue4",
  "darkturquoise", "green1", "yellow4", "yellow3","darkorange4", "brown",'black','forestgreen', 'red2', 'orange', 'cornflowerblue', 
  'magenta', 'darkolivegreen4', 'indianred1', 'tan4', 'darkblue', 
  'mediumorchid1','firebrick4',  'yellowgreen', 'lightsalmon', 'tan3',
  "tan1",'darkgray', 'wheat4', '#DDAD4B', 'chartreuse', 
  'seagreen1', 'moccasin', 'mediumvioletred', 'seagreen','cadetblue1',
  "darkolivegreen1" ,"tan2" ,   "tomato3" , "#7CE3D8","gainsboro","orange","yellow","red","maroon"
)

#Paths to BLAST
blast_bin <- "path/to/BLAST/ncbi-blast-2.16.0+/bin"
makeblastdb <- file.path(blast_bin, "makeblastdb")
blastn <- file.path(blast_bin, "blastn")

#Input data
types <- "all_viral_types_combined.fasta"
WW_reads <- "partial-seq_for_validation.fasta"
db_name <- "viral_Reference_Sequences"
excel_file <- "blast_top_hits_by_sample.xlsx"

reads <- readDNAStringSet(WW_reads)
remove_names <- c("EV-sp.", "EV-A", "EV-B", "EV-C", "EV-D",
                  "RV-A", "RV-B", "RV-C", "Coxsackievirus")

#Keep only sequences NOT in remove_names
WW_reads_filtered <- reads[!names(reads) %in% remove_names]

#Write the filtered sequences to a new FASTA
writeXStringSet(WW_reads_filtered, "partial-seq_for_validation.fasta")

fasta_lines <- readDNAStringSet(WW_reads)
seq_names <- names(fasta_lines)
uniqueID <- sprintf("ID%09d", seq_along(seq_names))
names(fasta_lines) <- paste0(uniqueID, "_", seq_names)

writeXStringSet(fasta_lines, "output_with_IDs.fasta")

WW_reads<- "output_with_IDs.fasta"

#Create BLAST database
if (!file.exists(paste0(db_name, ".nin"))) {
  cat("Creating BLAST database from reference file...\n")
  system(paste(shQuote(makeblastdb), "-in", types, "-dbtype nucl -out", db_name))
} else {
  cat("BLAST database already exists. Skipping creation.\n")
}

wb <- createWorkbook()

#To store total queries per sample
total_queries_list <- list()

```

```{r Blast}
#Run BLAST
cat("Running BLAST for", WW_reads, "...\n")

out_file <- sub("\\.fasta$", "_blast_results.txt", WW_reads)

#Run BLAST
system(paste("blastn -query", WW_reads, "-db", db_name, "-outfmt 6 -out ", out_file,"-task dc-megablast -num_threads 8 -evalue 1e-3 -word_size 11"))
query_seqs <- readDNAStringSet(WW_reads)
total_queries <- length(query_seqs)
total_queries_list[[WW_reads]] <- total_queries

#Skip if no hits
if (file.info(out_file)$size == 0) {
  warning("No hits found for ", WW_reads)
  results <- data.frame()
} else {
  results <- read.table(out_file, header = TRUE, sep = "\t",
                        col.names = c("query", "subject", "pident", "length",
                                      "mismatch", "gapopen", "qstart", "qend",
                                      "sstart", "send", "evalue", "bitscore"))
}

results$source_file <- WW_reads
attr(results, "total_queries") <- total_queries

uniqueID<-sprintf("ID%09d", 1:nrow(results))
results$uniqueID <- uniqueID

#Get top hit per query
if (nrow(results) > 0) {
  top_hits <- results %>%
    group_by(query) %>%
    top_n(1, bitscore) %>%
    ungroup()
} else {
  top_hits <- data.frame()
}

attr(top_hits, "total_queries") <- total_queries

#Clean Excel sheet name
sheet_name <- "VP1 partial seq"

#Remove ID from query name
top_hits$query <- substring(top_hits$query, 13)

top_hits <- top_hits %>%
  filter(top_hits[,1]!="EV-sp." & top_hits[,1] !="EV-A" & top_hits[,1] !="EV-B" & top_hits[,1] !="EV-C" & top_hits[,1] !="EV-D" & top_hits[,1] !="RV-A" & top_hits[,1] !="RV-B" & top_hits[,1] !="RV-C"
  )
total_queries <- length(top_hits)

top_hits <- top_hits %>%
  filter(!is.na(top_hits$subject),!is.na(top_hits$query))

#Write to workbook
addWorksheet(wb, sheet_name)
writeData(wb, sheet = sheet_name, top_hits)

#Save workbook with all top hits
saveWorkbook(wb, excel_file, overwrite = TRUE)
cat("Excel workbook written to", excel_file, "\n")
sheets <- getSheetNames(excel_file)

rightcalls <- data.frame(Actual=character(),call=character(),PercentIdentity=double(),ID=double())
wrongcalls <- data.frame(Actual=character(),call=character(),PercentIdentity=double(),ID=double())

for (i in 1:nrow(top_hits)) {
  if (top_hits[i,1]==top_hits[i,2]){
    rightcalls[i,]<-c(top_hits[i,1],top_hits[i,2],top_hits[i,3],top_hits[i,14])
  }else{
    wrongcalls[i,]<-c(top_hits[i,1],top_hits[i,2],top_hits[i,3],top_hits[i,14])
  }
}

rightcalls<-rightcalls %>%
  na.omit(rightcalls)
wrongcalls<-wrongcalls %>%
  na.omit(wrongcalls)
percentright<-(length(rightcalls$Actual)/(length(rightcalls$Actual)+length(wrongcalls$Actual)))*100

#Combine right and wrong calls
stacked_data <- rbind(
  data.frame(Actual = rightcalls$Actual, Type = "Right",PIdent = round(rightcalls$PercentIdentity,0)),
  data.frame(Actual = wrongcalls$Actual, Type = "Wrong",PIdent = round(wrongcalls$PercentIdentity,0))
)


#Calculate percentages
relative_abundance <- wrongcalls %>%
  group_by(Actual,call) %>%
  summarise(Count = n()) %>%
  mutate(prop = (Count / sum(Count)) * 100) %>%
  ungroup() 

stacked_percent <- stacked_data %>%
  group_by(Actual, Type) %>%
  summarise(Count = n(), .groups = "drop") %>%
  group_by(Actual) %>%
  mutate(Percent = (Count / sum(Count)) * 100)

stacked_data_PIdent <- stacked_data %>%
  group_by(Type,PIdent) %>%
  summarise(Count = n(), .groups = "drop") %>%
  group_by(Type) %>%
  mutate(Percent = (Count / (length(rightcalls$Actual)+length(wrongcalls$Actual))) * 100)

df<-as.data.frame(stacked_percent)
print(df)
print(length(unique(stacked_percent$Actual)))
print(sum(stacked_percent$Count))
percentright <- round(percentright,1)
```


```{r Plotting, fig.width = 20, fig.height = 10}

tiff("high_res_histo.tiff", units = "in", width = 7.5, height = 5, res = 600)
ggplot(stacked_data_PIdent,aes(x=PIdent,y=Percent,fill=Type)) +
  geom_col(color = "black") +
  scale_fill_manual(values = c("Right" = "forestgreen", "Wrong" = "firebrick"),labels = c("Right" = paste0("Right (",percentright,"%)"), "Wrong" = paste0("Wrong (",round(100-percentright,1),"%)"))) +
  labs(
    title = "Histogram of Genotyping Accuracy across percent identities with cutoff",
    x = "Percent Identity",
    y = "Percent (%)",
    fill = "Call Accuracy"
  ) +
  theme_minimal() +
  theme(legend.position = "bottom",
        axis.text.x = element_text(angle = 45, hjust = 1)
  ) 

tiff("high_stack_stacked.tiff", units = "in", width = 15, height = 10, res = 600)
#Plot stacked bar chart
ggplot(stacked_percent, aes(x = Actual, y = Percent, fill = Type)) +
  geom_col(color = "black") +
  scale_fill_manual(values = c("Right" = "forestgreen", "Wrong" = "firebrick")) +
  labs(
    title = "Percent Right vs Wrong Calls per Genotype with cutoff",
    x = "Genotype (Actual)",
    y = "% of Total Calls/Genotype",
    fill = "Call Accuracy"
  ) +
  theme_minimal() +
  theme(legend.position = "bottom",
        axis.text.x = element_text(angle = 45, hjust = 1)
  )
tiff("high_res_abundance.tiff", units = "in", width = 10, height = 7.5, res = 600)
ggplot(relative_abundance, aes(x = Actual, y = prop, fill = call)) +
  geom_col(color = "black") +
  scale_fill_manual(values = cArray) +
  labs(
    title = "Percent Wrong Calls per Genotype with cutoff",
    x = "Genotype (Actual)",
    y = "% of Wrong Calls/Genotype",
    fill = "Call"
  ) +
  theme_minimal() +
  theme(legend.position = "bottom",
        axis.text.x = element_text(angle = 45, hjust = 1)
  )


```

